from serial import Serial as ThirdySerial
from .pyserialperto import *
from .pyenvperto import *

pertoenv = Dotenv.load_file('.env')

pertoapi = (PertoApi()
    .setHandler.prefix(b'\x02')
    .setHandler.suffix(b'\x03')
    .setHandler.hash(ErrorDetect.bcc8)
    .setHandler.strip(Strip.regex(rb'\x02(.*?)\x03'))
    .setHandler(PertoHandler.simple)
    .setInterface.timeout('ack', 0.5)
    .setInterface.timeout('response', 5)
    .setInterface.timeout('between', 0.025)
    .setInterface.timeout('return_ack', True)
    #.setInterface.tries('number_of_tries', 3)
    #.setInterface.tries('time_between_tries', 0.05)
    .setInterface.serial('baudrate', 115200)
    .setInterface.serial_class(ThirdySerial)
    #.setInterface(PertoInterface.serial_with_tries)
    .setInterface(PertoInterface.serial)
    .setPipeline(PertoCommand.pipeline)
)

pertorelayapi1 = (PertoApi()
    .setHandler.prefix(b'\x02')
    .setHandler.suffix(b'\x03')
    .setHandler.hash(ErrorDetect.bcc8)
    .setHandler.strip(Strip.regex(rb'\x02(.*?)\x03'))
    .setHandler(PertoHandler.simple)
    .setInterface.timeout('ack', 0.5)
    .setInterface.timeout('cmd', 1)
    .setInterface.timeout('between', 0.25)
    .setInterface.timeout('return_ack', True)
    .setInterface.tries('number_of_tries', 3)
    .setInterface.tries('time_between_tries', 0)
    .setInterface.serial('baudrate', 115200)
    .setInterface.serial_class(ThirdySerial)
    .setInterface(PertoInterface.serial_with_tries)
    .setPipeline(PertoCommand.pipeline)
)
